### ISSUE TITLE
Fluxograma

### ISSUE THREAD

**Issue by tiagohm** [natanmorais/DescentralizedFileSharing#2]
Seria bom se alguém pudesse fazer o fluxograma de como será a interação entre as máquinas...
Tipo, descrever todo o caminho a ser percorrido desde a disponibilização do arquivo, sua transmissão e sua chegada até o destino final. Todas as regras e problemas que podem ocorrer durante.
Se for possível detalhem bem. Eu preciso ter uma base disso tudo pra poder codar. Eu não sei nem por onde começo e nem lembro de tudo q tem q fazer. Podem usar o [Astah](http://astah.net/download), [StartUML ](staruml.io) ou [Draw.io](https://www.draw.io/). Comitem. Viu @Haltielles e @natanmorais.

**Comment by natanmorais** [comment]
Criado Diagrama para 9 Casos distintos que o sistema pode apresentar.
